apiVersion: v1
kind: Service
metadata:
  labels:
    app: disco
  name: disco-controller-manager-metrics-service
  namespace: kube-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app: disco
