apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kube-system/disco-serving-cert
  name: disco-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: disco-webhook-service
      namespace: kube-system
      path: /mutate-disco-stable-sap-cc-v1-record
  failurePolicy: Fail
  name: mrecord.kb.io
  rules:
  - apiGroups:
    - disco.stable.sap.cc
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - records
  sideEffects: None
