/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/sapcc/kubernetes-operators/sentry/pkg/apis/sentry/v1"
	scheme "github.com/sapcc/kubernetes-operators/sentry/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SentryProjectsGetter has a method to return a SentryProjectInterface.
// A group's client should implement this interface.
type SentryProjectsGetter interface {
	SentryProjects(namespace string) SentryProjectInterface
}

// SentryProjectInterface has methods to work with SentryProject resources.
type SentryProjectInterface interface {
	Create(*v1.SentryProject) (*v1.SentryProject, error)
	Update(*v1.SentryProject) (*v1.SentryProject, error)
	UpdateStatus(*v1.SentryProject) (*v1.SentryProject, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.SentryProject, error)
	List(opts meta_v1.ListOptions) (*v1.SentryProjectList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SentryProject, err error)
	SentryProjectExpansion
}

// sentryProjects implements SentryProjectInterface
type sentryProjects struct {
	client rest.Interface
	ns     string
}

// newSentryProjects returns a SentryProjects
func newSentryProjects(c *SentryV1Client, namespace string) *sentryProjects {
	return &sentryProjects{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sentryProject, and returns the corresponding sentryProject object, and an error if there is any.
func (c *sentryProjects) Get(name string, options meta_v1.GetOptions) (result *v1.SentryProject, err error) {
	result = &v1.SentryProject{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sentryprojects").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SentryProjects that match those selectors.
func (c *sentryProjects) List(opts meta_v1.ListOptions) (result *v1.SentryProjectList, err error) {
	result = &v1.SentryProjectList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sentryprojects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sentryProjects.
func (c *sentryProjects) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sentryprojects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a sentryProject and creates it.  Returns the server's representation of the sentryProject, and an error, if there is any.
func (c *sentryProjects) Create(sentryProject *v1.SentryProject) (result *v1.SentryProject, err error) {
	result = &v1.SentryProject{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sentryprojects").
		Body(sentryProject).
		Do().
		Into(result)
	return
}

// Update takes the representation of a sentryProject and updates it. Returns the server's representation of the sentryProject, and an error, if there is any.
func (c *sentryProjects) Update(sentryProject *v1.SentryProject) (result *v1.SentryProject, err error) {
	result = &v1.SentryProject{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sentryprojects").
		Name(sentryProject.Name).
		Body(sentryProject).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *sentryProjects) UpdateStatus(sentryProject *v1.SentryProject) (result *v1.SentryProject, err error) {
	result = &v1.SentryProject{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sentryprojects").
		Name(sentryProject.Name).
		SubResource("status").
		Body(sentryProject).
		Do().
		Into(result)
	return
}

// Delete takes name of the sentryProject and deletes it. Returns an error if one occurs.
func (c *sentryProjects) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sentryprojects").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sentryProjects) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sentryprojects").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched sentryProject.
func (c *sentryProjects) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SentryProject, err error) {
	result = &v1.SentryProject{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sentryprojects").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
