/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/sapcc/kubernetes-operators/sentry/pkg/apis/sentry/v1"
	scheme "github.com/sapcc/kubernetes-operators/sentry/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SentryProjectsGetter has a method to return a SentryProjectInterface.
// A group's client should implement this interface.
type SentryProjectsGetter interface {
	SentryProjects(namespace string) SentryProjectInterface
}

// SentryProjectInterface has methods to work with SentryProject resources.
type SentryProjectInterface interface {
	Create(ctx context.Context, sentryProject *v1.SentryProject, opts metav1.CreateOptions) (*v1.SentryProject, error)
	Update(ctx context.Context, sentryProject *v1.SentryProject, opts metav1.UpdateOptions) (*v1.SentryProject, error)
	UpdateStatus(ctx context.Context, sentryProject *v1.SentryProject, opts metav1.UpdateOptions) (*v1.SentryProject, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.SentryProject, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.SentryProjectList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SentryProject, err error)
	SentryProjectExpansion
}

// sentryProjects implements SentryProjectInterface
type sentryProjects struct {
	client rest.Interface
	ns     string
}

// newSentryProjects returns a SentryProjects
func newSentryProjects(c *SentryV1Client, namespace string) *sentryProjects {
	return &sentryProjects{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sentryProject, and returns the corresponding sentryProject object, and an error if there is any.
func (c *sentryProjects) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SentryProject, err error) {
	result = &v1.SentryProject{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sentryprojects").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SentryProjects that match those selectors.
func (c *sentryProjects) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SentryProjectList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SentryProjectList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sentryprojects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sentryProjects.
func (c *sentryProjects) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sentryprojects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a sentryProject and creates it.  Returns the server's representation of the sentryProject, and an error, if there is any.
func (c *sentryProjects) Create(ctx context.Context, sentryProject *v1.SentryProject, opts metav1.CreateOptions) (result *v1.SentryProject, err error) {
	result = &v1.SentryProject{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sentryprojects").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sentryProject).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a sentryProject and updates it. Returns the server's representation of the sentryProject, and an error, if there is any.
func (c *sentryProjects) Update(ctx context.Context, sentryProject *v1.SentryProject, opts metav1.UpdateOptions) (result *v1.SentryProject, err error) {
	result = &v1.SentryProject{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sentryprojects").
		Name(sentryProject.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sentryProject).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *sentryProjects) UpdateStatus(ctx context.Context, sentryProject *v1.SentryProject, opts metav1.UpdateOptions) (result *v1.SentryProject, err error) {
	result = &v1.SentryProject{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sentryprojects").
		Name(sentryProject.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sentryProject).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the sentryProject and deletes it. Returns an error if one occurs.
func (c *sentryProjects) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sentryprojects").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sentryProjects) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sentryprojects").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched sentryProject.
func (c *sentryProjects) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SentryProject, err error) {
	result = &v1.SentryProject{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sentryprojects").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
