# permissions for end users to view records.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: record-viewer-role
rules:
- apiGroups:
  - disco.stable.sap.cc
  resources:
  - records
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - disco.stable.sap.cc
  resources:
  - records/status
  verbs:
  - get
