---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-disco-stable-sap-cc-v1-record
  failurePolicy: Fail
  name: mrecord.kb.io
  rules:
  - apiGroups:
    - disco.stable.sap.cc
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - records
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-disco-stable-sap-cc-v1-record
  failurePolicy: Fail
  name: vrecord.kb.io
  rules:
  - apiGroups:
    - disco.stable.sap.cc
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - records
  sideEffects: None
