// +build !ignore_autogenerated

/*******************************************************************************
*
* Copyright 2019 SAP SE
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You should have received a copy of the License along with this
* program. If not, you may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*
*******************************************************************************/

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/sapcc/kubernetes-operators/disco/pkg/apis/disco.stable.sap.cc/v1.DiscoRecord":       schema_pkg_apis_discostablesapcc_v1_DiscoRecord(ref),
		"github.com/sapcc/kubernetes-operators/disco/pkg/apis/disco.stable.sap.cc/v1.DiscoRecordList":   schema_pkg_apis_discostablesapcc_v1_DiscoRecordList(ref),
		"github.com/sapcc/kubernetes-operators/disco/pkg/apis/disco.stable.sap.cc/v1.DiscoRecordSpec":   schema_pkg_apis_discostablesapcc_v1_DiscoRecordSpec(ref),
		"github.com/sapcc/kubernetes-operators/disco/pkg/apis/disco.stable.sap.cc/v1.DiscoRecordStatus": schema_pkg_apis_discostablesapcc_v1_DiscoRecordStatus(ref),
	}
}

func schema_pkg_apis_discostablesapcc_v1_DiscoRecord(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DiscoRecord is a specification for a DiscoRecord resource",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Description: "Specification of the DiscoRecord.",
							Ref:         ref("github.com/sapcc/kubernetes-operators/disco/pkg/apis/disco.stable.sap.cc/v1.DiscoRecordSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Description: "Status of the DiscoRecord.",
							Ref:         ref("github.com/sapcc/kubernetes-operators/disco/pkg/apis/disco.stable.sap.cc/v1.DiscoRecordStatus"),
						},
					},
				},
				Required: []string{"spec", "status"},
			},
		},
		Dependencies: []string{
			"github.com/sapcc/kubernetes-operators/disco/pkg/apis/disco.stable.sap.cc/v1.DiscoRecordSpec", "github.com/sapcc/kubernetes-operators/disco/pkg/apis/disco.stable.sap.cc/v1.DiscoRecordStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_discostablesapcc_v1_DiscoRecordList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DiscoRecordList is a list of DiscoRecord resources",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ListMeta"),
						},
					},
					"items": {
						SchemaProps: spec.SchemaProps{
							Description: "List of DiscoRecords.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/sapcc/kubernetes-operators/disco/pkg/apis/disco.stable.sap.cc/v1.DiscoRecord"),
									},
								},
							},
						},
					},
				},
				Required: []string{"metadata", "items"},
			},
		},
		Dependencies: []string{
			"github.com/sapcc/kubernetes-operators/disco/pkg/apis/disco.stable.sap.cc/v1.DiscoRecord", "k8s.io/apimachinery/pkg/apis/meta/v1.ListMeta"},
	}
}

func schema_pkg_apis_discostablesapcc_v1_DiscoRecordSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DiscoRecordSpec is the spec for a DiscoRecord resource",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"type": {
						SchemaProps: spec.SchemaProps{
							Description: "Type of the DNS record. Currently supported are A, CNAME, SOA, NS records.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"hosts": {
						SchemaProps: spec.SchemaProps{
							Description: "List of hostnames.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
					"record": {
						SchemaProps: spec.SchemaProps{
							Description: "The record to use.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"zoneName": {
						SchemaProps: spec.SchemaProps{
							Description: "Optional zone for the record.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"description": {
						SchemaProps: spec.SchemaProps{
							Description: "Optional description for the record.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"type", "hosts", "record"},
			},
		},
	}
}

func schema_pkg_apis_discostablesapcc_v1_DiscoRecordStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DiscoRecordStatus is the status for a DiscoRecord resource",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"recordsetStatus": {
						SchemaProps: spec.SchemaProps{
							Description: "The status of the record.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"recordsetStatus"},
			},
		},
	}
}
